# Generated by Django 4.1.4 on 2023-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_category_options_alter_person_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
