# Generated by Django 4.1.4 on 2023-01-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_idea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
