# Generated by Django 4.1.4 on 2023-01-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_idea_is_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
