# Generated by Django 4.1.4 on 2023-01-04 19:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_rename_is_acitve_idea_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
