# Generated by Django 4.1.4 on 2023-01-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_idea_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_image',
            field=models.ImageField(blank=True, null=True, upload_to='ideas'),
        ),
    ]
