# Generated by Django 4.1.4 on 2023-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_alter_idea_idea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='persons'),
        ),
    ]
