# Generated by Django 4.1.4 on 2023-01-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_alter_person_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_url',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
