# Generated by Django 4.1.4 on 2023-01-04 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_comment_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='point',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
